{
  "CVE Code": "CVE-2022-0718",
  "Published": "2022-08-29T14:03:04",
  "Updated": "2024-08-02T23:40:03.318Z",
  "Description": "A flaw was found in python-oslo-utils. Due to improper parsing, passwords with a double quote ( \" ) in them cause incorrect masking in debug logs, causing any part of the password after the double quote to be plaintext.",
  "ProblemTypes": [
    "CWE-522 - Insufficiently Protected Credentials"
  ],
  "Affected": [
    {
      "vendor": "n/a",
      "product": "openstack/python-oslo.utils",
      "versions": [
        "Affects all versions, Fixed in 4.10.1, 4.12.1."
      ]
    }
  ],
  "Reference": [
    "https://bugzilla.redhat.com/show_bug.cgi?id=2056850",
    "https://bugs.launchpad.net/oslo.utils/+bug/1949623",
    "https://opendev.org/openstack/oslo.utils/commit/6e17ae1f7959c64dfd20a5f67edf422e702426aa",
    "https://security-tracker.debian.org/tracker/CVE-2022-0718",
    "https://access.redhat.com/security/cve/CVE-2022-0718",
    "https://lists.debian.org/debian-lts-announce/2022/09/msg00015.html"
  ]
}