{
  "CVE Code": "CVE-2012-2135",
  "Published": "2012-08-14T22:00:00",
  "Updated": "2024-08-06T19:26:09.000Z",
  "Description": "The utf-16 decoder in Python 3.1 through 3.3 does not update the aligned_end variable after calling the unicode_decode_call_errorhandler function, which allows remote attackers to obtain sensitive information (process memory) or cause a denial of service (memory corruption and crash) via unspecified vectors.",
  "ProblemTypes": [
    "n/a"
  ],
  "Affected": [
    {
      "vendor": "n/a",
      "product": "n/a",
      "versions": [
        "n/a"
      ]
    }
  ],
  "Reference": [
    "http://www.ubuntu.com/usn/USN-1615-1",
    "http://secunia.com/advisories/51087",
    "http://www.ubuntu.com/usn/USN-1616-1",
    "http://bugs.python.org/issue14579",
    "http://secunia.com/advisories/51089",
    "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=670389",
    "http://www.openwall.com/lists/oss-security/2012/04/25/4",
    "http://www.openwall.com/lists/oss-security/2012/04/25/2"
  ]
}