{
  "CVE Code": "CVE-2021-46823",
  "Published": "2022-06-18T15:27:17",
  "Updated": "2024-08-04T05:17:42.836Z",
  "Description": "python-ldap before 3.4.0 is vulnerable to a denial of service when ldap.schema is used for untrusted schema definitions, because of a regular expression denial of service (ReDoS) flaw in the LDAP schema parser. By sending crafted regex input, a remote authenticated attacker could exploit this vulnerability to cause a denial of service condition.",
  "ProblemTypes": [
    "n/a"
  ],
  "Affected": [
    {
      "vendor": "n/a",
      "product": "n/a",
      "versions": [
        "n/a"
      ]
    }
  ],
  "Reference": [
    "https://github.com/python-ldap/python-ldap/security/advisories/GHSA-r8wq-qrxc-hmcm",
    "https://exchange.xforce.ibmcloud.com/vulnerabilities/221507"
  ]
}